name: Composite action example
description: An example of a composite action that runs multiple steps.

inputs:
    name:
        description: Enter your name
        required: true
        default: John Doe

outputs:
    status:
        description: The status of the action
        value: ${{ steps.wish.outputs.status }}
    
runs:
    using: composite
    steps:
      - name: Wish me
        id: wish
        shell: bash
        run: |
            echo "Hello ${{ inputs.name }}"
            echo "status=success" >> $GITHUB_OUTPUT




          