name: Composite action example
description: An example of a composite action that runs multiple steps.

inputs:
    name:
        description: Enter your name
        required: true
        default: John Doe
    
runs:
    using: composite
    steps:
      - name: Wish me
        shell: bash
        run: |
            echo "Hello ${{ inputs.name }}"



          