name: Composite action demo
description: A composite action to wish someone

inputs:
    course:
        description: Enter course name
        required: true
        default: "DevOps"

outputs:
    status:
        description: get the status of the run
        value: ${{ steps.course.outputs.status }}

runs:
  using: composite
  steps:
    - name: print course
      id: course
      shell: bash
      run: |
        echo "I am learning ${{ inputs.course }}"
        echo "status=success" >> $GITHUB_OUTPUT
