name: Composite action demo
on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: checkout action
              uses: actions/checkout@v4
            
            - name: Print course
              id: course
              uses: ./.github/workflows/composite-action
              with:
                name: "Cyber security"

            - name: Check output
              run: echo "The status of the action is ${{ steps.course.outputs.status }}"
              
        