name: Concurrency in github actions
on: push

# cancel-in-progress: false # default value, if set to false, the new run will be added to the queue and will run after the current run is finished
# cancel-in-progress: true # if set to true, the new run will cancel the current run and only the latest run will be executed.
concurrency:
    group: test-${{ github.ref_name }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Start
              run: echo "started run"

            - name: Sleep
              run: sleep 60

            - name: End
              run: echo "Finished run"