name: Matrix - parallel execution demo
on:
    push:
        branches: [ master ]
jobs:
    test:
        if: github.ref == 'master'
        runs-on: ubuntu-latest
        strategy:
            matrix: 
                node: [12, 14, 16]
                # exclude node versions 12 and 14 for demonstration purposes
                exclude:
                    - node: 12
                    - node: 14
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            
            - name: Set up Node.js ${{ matrix.node }}
              uses: actions/setup-node@v2   
              with:
                node-version: ${{ matrix.node }}
            
            - name: Print node version
              run: node -v
              