name: Reusable workflow Demo
on:
    workflow_call:
      secrets: 
        SAMPLE_SECRET:
            required: true


      inputs:
        node-version:
            description: Node version
            type: string
            required: true
        

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ inputs.node-version }}

            - name: install the packages
              run: npm install
            
            - name: print the secret value
              run: echo "The secret value is $SAMPLE_SECRET"
              env:
                SAMPLE_SECRET: ${{ secrets.SAMPLE_SECRET }}