name: Input and Output variables in github actions
on: 
    workflow_dispatch:
        inputs:
            environment: 
                description: "Enter environment"
                required: true
                default: "Dev"
            
        

jobs:
    demo:
        runs-on: ubuntu-latest

        steps:
            - name: Generate environment
              id: environment_step
              run: |
                ENVIRONMENT="${{ github.event.inputs.environment }}"
                echo "message=running in $ENVIRONMENT" >> $GITHUB_OUTPUT

            - name: Print environment
              run: echo "${{ steps.environment_step.outputs.message }}"